### ISSUE TITLE
javax dependency issue

### ISSUE THREAD

**Issue by bloohunnits** [sdaschner/java-playground#1]
trying to send email gets past auth browser pop part but then throws this please advise my pom
 should be good can provide if needed

java.lang.IllegalAccessError: failed to access class com.sun.activation.registries.LogSupport from class javax.activation.MailcapCommandMap (com.sun.activation.registries.LogSupport and javax.activation.MailcapCommandMap are in unnamed module of loader 'app')
	at javax.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:140) ~[activation-1.1.jar:1.1]
	at javax.activation.CommandMap.getDefaultCommandMap(CommandMap.java:61) ~[activation-1.1.jar:1.1]
	at javax.activation.DataHandler.getCommandMap(DataHandler.java:153) ~[activation-1.1.jar:1.1]
	at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:611) ~[activation-1.1.jar:1.1]
	at javax.activation.DataHandler.writeTo(DataHandler.java:315) ~[activation-1.1.jar:1.1]
	at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:340) ~[javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1575) ~[javax.mail-1.6.2.jar:1.6.2]

**Comment by bloohunnits** [comment]
not sure what the issue was but this is resolved used a slightly different way copied  from google docs thanks

**Comment by sdaschner** [comment]
> used a slightly different way copied from google docs thanks

Not sure what you meant by that, but glad it's resolved.
